# Generated by Django 4.2.2 on 2023-06-20 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_inicio', models.DateTimeField(null=True)),
                ('data_fim', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.local'),
        ),
    ]
