# Generated by Django 4.2.2 on 2023-06-27 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0003_convidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='convidados',
            field=models.ManyToManyField(to='agenda.convidado'),
        ),
        migrations.AddField(
            model_name='convidado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
