# Generated by Django 4.2.2 on 2023-06-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_compromisso_convidados_convidado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='locais'),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='local',
            name='rua',
            field=models.CharField(max_length=120),
        ),
    ]
